name: ag-shrna
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - jinja2
  - matplotlib
  - seaborn
  - anndata
  - grpcio
  - pip:
      - git+https://github.com/google-deepmind/alphagenome

